---
# Channel to use for the OpenShift Virtualization subscription
# When not set (or set to "") use the default channel for the
# OpenShift version this operator is installed on. If there is
# no matching version use the `defaultChannel`
ocp4_workload_openshift_virtualization_channel: stable

# Set automatic InstallPlan approval. Must be set to false when specifying a starting_csv
ocp4_workload_openshift_virtualization_automatic_install_plan_approval: true

# Set a starting ClusterServiceVersion.
# Recommended to leave empty to get latest in the channel when not
# using a catalog snapshot.
# Highly recommended to be set when using a catalog snapshot but can be
# empty to get the latest available in the channel at the time when
# the catalog snapshot got created.
ocp4_workload_openshift_virtualization_starting_csv: ""
# ocp4_workload_openshift_virtualization_starting_csv: "kubevirt-hyperconverged-operator.v4.19.6"

# Add additional tolerations to the HyperConverged components
# This is necessary in mixed worker node environment where nodes that can run
# VMs are tainted to prevent other pods from running on them
ocp4_workload_openshift_virtualization_workload_tolerations: []
# Example: tolerate all nodes that have a taint with key 'metal'
# ocp4_workload_openshift_virtualization_workload_tolerations:
# - key: metal
#   operator: Exists

# Use Snapshots for boot sources - which is the default
# For deployments on top of CNV with Ceph set to false
# When set to false CNV is configured to use PVCs for boot sources
# which elminiates VolumeSnapshots without associated PVCs
ocp4_workload_openshift_virtualization_boot_sources_shapshot: true

# For AWS it is possible to use KubeVirt without a metal node
# For that the subscription for the operator needs to have special config
# whih will be added if the following variable is set to true
ocp4_workload_openshift_virtualization_enabled_nested_kvm: false

# Deploy the Hyperconverged Object. Defaults to true
# Only set to false if a lab needs students to create it
ocp4_workload_openshift_virtualization_deploy_hyperconverged: true

# Install virtctl - requires hyperconverged to be deployed
ocp4_workload_openshift_virtualization_install_virtctl: true

# --------------------------------
# Operator Catalog Snapshot Settings
# --------------------------------
# See https://github.com/redhat-cop/agnosticd/blob/development/docs/Operator_Catalog_Snapshots.adoc
# for instructions on how to set up catalog snapshot images

# Use a catalog snapshot
ocp4_workload_openshift_virtualization_use_catalog_snapshot: false

# Catalog Source Name when using a catalog snapshot. This should be unique
# in the cluster to avoid clashes
ocp4_workload_openshift_virtualization_catalogsource_name: redhat-operators-snapshot-kubevirt

# Catalog snapshot image
ocp4_workload_openshift_virtualization_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog

# Catalog snapshot image tag
ocp4_workload_openshift_virtualization_catalog_snapshot_image_tag: "v4.19_2025_10_06"
