---
# Main entry point for the workload
- name: Running Pre Workload Tasks
  ansible.builtin.include_tasks:
    file: ./pre_workload.yml
    apply:
      become: "{{ become_override | default(omit) }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload Tasks
  ansible.builtin.include_tasks:
    file: ./workload.yml
    apply:
      become: "{{ become_override | default(omit) }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Post Workload Tasks
  ansible.builtin.include_tasks:
    file: ./post_workload.yml
    apply:
      become: "{{ become_override | default(omit) }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Remove Workload Tasks
  ansible.builtin.include_tasks:
    file: ./remove_workload.yml
    apply:
      become: "{{ become_override | default(omit) }}"
  when: ACTION == "remove" or ACTION == "destroy"
