---
- name: Pre Workload Tasks
  ansible.builtin.debug:
    msg: "Pre-Workload tasks starting for Compliance Operator"

- name: Ensure openshift-compliance namespace exists
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_days_workload_compliance_operator_namespace }}"
  register: r_namespace
  until: r_namespace is successful
  retries: 10
  delay: 5
