---
- name: Remove ACM MultiCluster Observability
  k8s:
    state: absent
    definition: "{{ lookup('template','./templates/multiclusterobservability-cr.yml.j2') | from_yaml }}"

- name: Get Bucket information part 1
  k8s_info:
    api_version: v1
    kind: ConfigMap
    name: observer-bucket
    namespace: "{{ ocp4_workload_acm_multicluster_observability_namespace }}"
  register: r_bucket_cm

- name: Get Bucket information part 2
  k8s_info:
    api_version: v1
    kind: Secret
    name: observer-bucket
    namespace: "{{ ocp4_workload_acm_multicluster_observability_namespace }}"
  register: r_bucket_secret

- name: Remove Thanos Object Storage Secret
  k8s:
    state: absent
    definition: "{{ lookup('template','./templates/thanos-object-storage-secret.yml.j2') | from_yaml }}"

- name: Remove Object Bucket Claim
  k8s:
    state: absent
    definition: "{{ lookup('template','./templates/obc-observability.yml.j2') | from_yaml }}"

- name: Remove MultCluster Observability Namespace
  k8s:
    state: absent
    definition: "{{ lookup('template','./templates/namespace_create.yml.j2') | from_yaml }}"

- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent | bool
