---
ocp4_workload_rhacs_install_operator_namespace: rhacs-operator
ocp4_workload_rhacs_install_operator_channel: rhacs-4.9

ocp4_workload_rhacs_install_operator_use_catalog_snapshot: false
ocp4_workload_rhacs_install_operator_catalog_source_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_rhacs_install_operator_catalog_source_tag: "v4.15_2024_04_08"

ocp4_workload_rhacs_automatic_install_plan_approval: true
ocp4_workload_rhacs_install_operator_starting_csv: ""

ocp4_workload_rhacs_central_namespace: stackrox
# Enable the new V4 central scanner
ocp4_workload_rhacs_enable_central_scanner_v4: false

# To avoid browser cert nag screens, this adds the Stackrox CA cert to the Route for Central.
# change this once we're happy that it works consistently
ocp4_workload_rhacs_enable_route_certs: true

# Enable collector config for rhacs 4.8+
ocp4_workload_rhacs_collector_config_enable: false
ocp4_workload_rhacs_collector_config_expternal_ips_enable: true

# Set the default password for the Central admin user (empty will generate a random password)
ocp4_workload_rhacs_central_admin_password: ""
ocp4_workload_rhacs_central_admin_password_length: 18
